apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: inflate
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
          resources:
            requests:
              cpu: 0.5
      nodeSelector:
        role: "cpu-micro"
      tolerations:
        - key: "cpu-micro"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
